export const iconMap = {
  home: 'navigation/home',
  homeOutline: 'navigation/home-outline',
  search: 'navigation/search',
  searchOutline: 'navigation/search-outline',
  message: 'navigation/message',
  messageOutline: 'navigation/message-outline',
  mine: 'navigation/mine',
  mineOutline: 'navigation/mine-outline',
  publish: 'navigation/publish',
  publish2: 'navigation/publish2',

  mineAddOutline: 'mine/add-outline',
  minePost: 'mine/post',
  mineEarn: 'mine/earn',
  mineBuy: 'mine/buy',
  mineCollect: 'mine/collect',
  mineBeCreator: 'mine/be-creator',
  mineSet: 'mine/set',
  mineSetAcc: 'mine/set-acc',
  mineSetPw: 'mine/set-pw',
  mineSetPrefer: 'mine/set-prefer',
  mineSetBlock: 'mine/set-block',
  mineSetDelAcc: 'mine/set-delacc',
  mineLang: 'mine/lang',
  mineAbout: 'mine/about',
  mineAboutTos: 'mine/about-tos',
  mineAboutPp: 'mine/about-pp',
  mineAboutCp: 'mine/about-cp',
  mineAboutDmca: 'mine/about-dmca',
  mineAboutVersion: 'mine/about-version',
  mineLogout: 'mine/logout',

  analysis: 'function/analysis',
  attach: 'function/attach',
  back: 'function/back',
  block: 'function/block',
  calendar: 'function/calendar',
  close: 'function/close',
  closeWhite: 'function/close-white',
  collection: 'function/collection',
  checkPrimary: 'function/check-primary',
  draft: 'function/draft',
  drop: 'function/drop',
  dropdown: 'function/dropdown',
  emoji: 'function/emoji',
  filter: 'function/filter',
  gif: 'function/gif',
  location: 'function/location',
  messagePrimary: 'function/message-primary',
  moreHorizontal: 'function/more-horizontal',
  moreVertical: 'function/more-vertical',
  picture: 'function/picture',
  play: 'function/play',
  replay: 'function/replay',
  report: 'function/report',
  search2: 'function/search',
  send: 'function/send',
  sendWhite: 'function/send-white',
  setting: 'function/setting',
  sharePage: 'function/share-page',
  video: 'function/video',
  videoWhite: 'function/video-white',
  link: 'function/link',
  bin: 'function/bin',
  camera: 'function/camera',
  cameraWhite: 'function/camera-white',
  cameraCapture: 'function/camera-capture',
  cameraFlip: 'function/camera-flip',
  driverLicense: 'function/driver-license',
  identityCard: 'function/identity-card',
  passport: 'function/passport',
  focal: 'function/focal',
  questionOutline: 'function/question-outline',
  ellipse: 'function/ellipse',

  comment: 'interaction/comment',
  likeOutline: 'interaction/like-outline',
  like: 'interaction/like',
  sharePost: 'interaction/share-post',
  checkActive: 'interaction/check-active',
  check: 'interaction/check',
  circleSuccess: 'interaction/circle-success',
  circleError: 'interaction/circle-error',

  apple: 'login/apple',
  facebook: 'login/facebook',
  google: 'login/google',
  twitter: 'login/twitter',
  mail: 'login/mail',
  account: 'login/account',
  pwdOpen: 'login/pwd-open',
  pwdClose: 'login/pwd-close',

  socialInstagram: 'social/instagram',
  socialFacebook: 'social/facebook',
  socialTwitter: 'social/twitter',
  socialYoutube: 'social/youtube',
  socialTiktok: 'social/tiktok',

  instagramActive: 'social/instagram-active',
  instagramDeactive: 'social/instagram-deactive',

  facebookActive: 'social/facebook-active',
  facebookDeactive: 'social/facebook-deactive',

  twitterActive: 'social/twitter-active',
  twitterDeactive: 'social/twitter-deactive',

  youtubeActive: 'social/youtube-active',
  youtubeDeactive: 'social/youtube-deactive',

  tiktokActive: 'social/tiktok-active',
  tiktokDeactive: 'social/tiktok-deactive',

  officialEarth: 'officialMenu/earth',
  officialLogo: 'officialMenu/logo',
  officialMenu: 'officialMenu/menu',
  officialNavLogo: 'officialMenu/nav-logo',
  officialReverseLogo: 'officialMenu/reverse-logo',
}
