export const iconMap = {
  home: { path: 'navigation/home', preload: true },
  homeOutline: { path: 'navigation/home-outline', preload: true },
  search: { path: 'navigation/search', preload: true },
  searchOutline: { path: 'navigation/search-outline', preload: true },
  message: { path: 'navigation/message', preload: true },
  messageOutline: { path: 'navigation/message-outline', preload: true },
  mine: { path: 'navigation/mine', preload: true },
  mineOutline: { path: 'navigation/mine-outline', preload: true },
  publish: { path: 'navigation/publish', preload: true },
  publish2: { path: 'navigation/publish2', preload: true },

  mineAddOutline: { path: 'mine/add-outline' },
  minePost: { path: 'mine/post' },
  mineEarn: { path: 'mine/earn' },
  mineBuy: { path: 'mine/buy' },
  mineCollect: { path: 'mine/collect' },
  mineBeCreator: { path: 'mine/be-creator' },
  mineSet: { path: 'mine/set' },
  mineSetAcc: { path: 'mine/set-acc' },
  mineSetPw: { path: 'mine/set-pw' },
  mineSetPrefer: { path: 'mine/set-prefer' },
  mineSetBlock: { path: 'mine/set-block' },
  mineSetDelAcc: { path: 'mine/set-delacc' },
  mineLang: { path: 'mine/lang' },
  mineAbout: { path: 'mine/about' },
  mineAboutTos: { path: 'mine/about-tos' },
  mineAboutPp: { path: 'mine/about-pp' },
  mineAboutCp: { path: 'mine/about-cp' },
  mineAboutDmca: { path: 'mine/about-dmca' },
  mineAboutVersion: { path: 'mine/about-version' },
  mineLogout: { path: 'mine/logout' },

  analysis: { path: 'function/analysis' },
  attach: { path: 'function/attach' },
  back: { path: 'function/back' },
  block: { path: 'function/block' },
  calendar: { path: 'function/calendar' },
  close: { path: 'function/close' },
  closeWhite: { path: 'function/close-white' },
  collection: { path: 'function/collection' },
  checkPrimary: { path: 'function/check-primary' },
  draft: { path: 'function/draft' },
  drop: { path: 'function/drop' },
  dropdown: { path: 'function/dropdown' },
  emoji: { path: 'function/emoji' },
  filter: { path: 'function/filter' },
  gif: { path: 'function/gif' },
  location: { path: 'function/location' },
  messagePrimary: { path: 'function/message-primary' },
  moreHorizontal: { path: 'function/more-horizontal' },
  moreVertical: { path: 'function/more-vertical' },
  picture: { path: 'function/picture' },
  play: { path: 'function/play', preload: true },
  replay: { path: 'function/replay', preload: true },
  report: { path: 'function/report' },
  search2: { path: 'function/search' },
  send: { path: 'function/send' },
  sendWhite: { path: 'function/send-white' },
  setting: { path: 'function/setting' },
  sharePage: { path: 'function/share-page' },
  video: { path: 'function/video' },
  videoWhite: { path: 'function/video-white' },
  link: { path: 'function/link' },
  bin: { path: 'function/bin' },
  camera: { path: 'function/camera' },
  cameraWhite: { path: 'function/camera-white' },
  cameraCapture: { path: 'function/camera-capture' },
  cameraFlip: { path: 'function/camera-flip' },
  driverLicense: { path: 'function/driver-license' },
  identityCard: { path: 'function/identity-card' },
  passport: { path: 'function/passport' },
  focal: { path: 'function/focal' },
  questionOutline: { path: 'function/question-outline' },
  ellipse: { path: 'function/ellipse' },
  info: { path: 'function/info' },

  comment: { path: 'interaction/comment' },
  likeOutline: { path: 'interaction/like-outline', preload: true },
  like: { path: 'interaction/like', preload: true },
  sharePost: { path: 'interaction/share-post' },
  checkActive: { path: 'interaction/check-active' },
  check: { path: 'interaction/check' },
  circleSuccess: { path: 'interaction/circle-success' },
  circleError: { path: 'interaction/circle-error' },

  apple: { path: 'login/apple' },
  facebook: { path: 'login/facebook' },
  google: { path: 'login/google' },
  twitter: { path: 'login/twitter' },
  mail: { path: 'login/mail' },
  account: { path: 'login/account' },
  pwdOpen: { path: 'login/pwd-open', preload: true },
  pwdClose: { path: 'login/pwd-close', preload: true },

  socialInstagram: { path: 'social/instagram' },
  socialFacebook: { path: 'social/facebook' },
  socialTwitter: { path: 'social/twitter' },
  socialYoutube: { path: 'social/youtube' },
  socialTiktok: { path: 'social/tiktok' },

  instagramActive: { path: 'social/instagram-active' },
  instagramDeactive: { path: 'social/instagram-deactive' },

  facebookActive: { path: 'social/facebook-active' },
  facebookDeactive: { path: 'social/facebook-deactive' },

  twitterActive: { path: 'social/twitter-active' },
  twitterDeactive: { path: 'social/twitter-deactive' },

  youtubeActive: { path: 'social/youtube-active' },
  youtubeDeactive: { path: 'social/youtube-deactive' },

  tiktokActive: { path: 'social/tiktok-active' },
  tiktokDeactive: { path: 'social/tiktok-deactive' },

  officialDropdown: { path: 'official/dropdown' },
  officialEarth: { path: 'official/earth' },
  officialLogo: { path: 'official/logo' },
  officialMenu: { path: 'official/menu' },
  officialNavLogo: { path: 'official/nav-logo' },
  officialReverseLogo: { path: 'official/reverse-logo' },
}
