export const iconMap = {
  home: 'navigation/home',
  homeOutline: 'navigation/home-outline',
  search: 'navigation/search',
  searchOutline: 'navigation/search-outline',
  message: 'navigation/message',
  messageOutline: 'navigation/message-outline',
  mine: 'navigation/mine',
  mineOutline: 'navigation/mine-outline',
  publish: 'navigation/publish',
  publish2: 'navigation/publish2',

  analysis: 'function/analysis',
  attach: 'function/attach',
  back: 'function/back',
  calendar: 'function/calendar',
  close: 'function/close',
  closeWhite: 'function/close-white',
  collection: 'function/collection',
  draft: 'function/draft',
  drop: 'function/drop',
  dropdown: 'function/dropdown',
  emoji: 'function/emoji',
  filter: 'function/filter',
  gif: 'function/gif',
  location: 'function/location',
  moreHorizontal: 'function/more-horizontal',
  moreVertical: 'function/more-vertical',
  picture: 'function/picture',
  play: 'function/play',
  report: 'function/report',
  search2: 'function/search',
  send: 'function/send',
  sendWhite: 'function/send-white',
  setting: 'function/setting',
  sharePage: 'function/share-page',
  video: 'function/video',
  link: 'function/link',
  bin: 'function/bin',
  camera: 'function/camera',

  comment: 'interaction/comment',
  likeOutline: 'interaction/like-outline',
  like: 'interaction/like',
  sharePost: 'interaction/share-post',

  apple: 'login/apple',
  facebook: 'login/facebook',
  google: 'login/google',
  twitter: 'login/twitter',
  mail: 'login/mail',
  account: 'login/account',
  pwdOpen: 'login/pwd-open',
  pwdClose: 'login/pwd-close',

  socialInstagram: 'social/instagram',
  socialFacebook: 'social/facebook',
  socialTwitter: 'social/twitter',
  socialYoutube: 'social/youtube',
  socialTiktok: 'social/tiktok',
}
