name: vida
volumes:
  node_modules:
services:
  # node:
  #   image: node:16.19.0
  #   container_name: vida_node
  #   ports:
  #     - ${PORT}:${PORT}
  #   expose:
  #     - ${PORT}
  #   volumes:
  #     - ${PROJ}:/var/www/html
  #     - node_modules:/var/www/html/node_modules
  #   tty: true
  #   working_dir: /var/www/html
  #   command: bash -c "npm install && npm run dev"

  nginx:
    image: nginx:latest
    container_name: vida_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/templates
      - ${SSL_CERT}:/etc/nginx/ssl/site.crt
      - ${SSL_KEY}:/etc/nginx/ssl/site.key
    environment:
      - IP=${IP}
